### ISSUE TITLE
Where is it.

### ISSUE THREAD

**Issue by bloved** [alex-0ff/csgowallhack#8]
Hello,

Push the button "insert" to close the menu and then you can play

_Originally posted by @alexandrecoulay in https://github.com/alex-0ff/csgowallhack/issues/6#issuecomment-784121935_

Where is the insert button, my good sir?

**Comment by alexandrecoulay** [comment]
> Hello,
> 
> Push the button "insert" to close the menu and then you can play
> 
> _Originally posted by @alexandrecoulay in https://github.com/alex-0ff/csgowallhack/issues/6#issuecomment-784121935_
> 
> Where is the insert button, my good sir?

Here : https://images.app.goo.gl/qmFwKEh9YJwjWyig7
